// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/AvengeMedia/dankcalendar/core/internal/calendar"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduleReader creates a new instance of MockScheduleReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockScheduleReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockScheduleReader is an autogenerated mock type for the ScheduleReader type
type MockScheduleReader struct {
	mock.Mock
}

type MockScheduleReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleReader) EXPECT() *MockScheduleReader_Expecter {
	return &MockScheduleReader_Expecter{mock: &_m.Mock}
}

// ReadSchedule provides a mock function for the type MockScheduleReader
func (_mock *MockScheduleReader) ReadSchedule(ctx context.Context, email string, from time.Time, to time.Time) (*calendar.Schedule, error) {
	ret := _mock.Called(ctx, email, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ReadSchedule")
	}

	var r0 *calendar.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (*calendar.Schedule, error)); ok {
		return returnFunc(ctx, email, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) *calendar.Schedule); ok {
		r0 = returnFunc(ctx, email, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calendar.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, email, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleReader_ReadSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSchedule'
type MockScheduleReader_ReadSchedule_Call struct {
	*mock.Call
}

// ReadSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - from time.Time
//   - to time.Time
func (_e *MockScheduleReader_Expecter) ReadSchedule(ctx any, email any, from any, to any) *MockScheduleReader_ReadSchedule_Call {
	return &MockScheduleReader_ReadSchedule_Call{Call: _e.mock.On("ReadSchedule", ctx, email, from, to)}
}

func (_c *MockScheduleReader_ReadSchedule_Call) Run(run func(ctx context.Context, email string, from time.Time, to time.Time)) *MockScheduleReader_ReadSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScheduleReader_ReadSchedule_Call) Return(schedule *calendar.Schedule, err error) *MockScheduleReader_ReadSchedule_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleReader_ReadSchedule_Call) RunAndReturn(run func(ctx context.Context, email string, from time.Time, to time.Time) (*calendar.Schedule, error)) *MockScheduleReader_ReadSchedule_Call {
	_c.Call.Return(run)
	return _c
}
