// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/AvengeMedia/dankcalendar/core/internal/notify"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Dismiss provides a mock function for the type MockSender
func (_mock *MockSender) Dismiss(id uint32) {
	_mock.Called(id)
	return
}

// MockSender_Dismiss_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dismiss'
type MockSender_Dismiss_Call struct {
	*mock.Call
}

// Dismiss is a helper method to define mock.On call
//   - id uint32
func (_e *MockSender_Expecter) Dismiss(id any) *MockSender_Dismiss_Call {
	return &MockSender_Dismiss_Call{Call: _e.mock.On("Dismiss", id)}
}

func (_c *MockSender_Dismiss_Call) Run(run func(id uint32)) *MockSender_Dismiss_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_Dismiss_Call) Return() *MockSender_Dismiss_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSender_Dismiss_Call) RunAndReturn(run func(id uint32)) *MockSender_Dismiss_Call {
	_c.Run(run)
	return _c
}

// OpenURI provides a mock function for the type MockSender
func (_mock *MockSender) OpenURI(uri string) error {
	ret := _mock.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for OpenURI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(uri)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_OpenURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenURI'
type MockSender_OpenURI_Call struct {
	*mock.Call
}

// OpenURI is a helper method to define mock.On call
//   - uri string
func (_e *MockSender_Expecter) OpenURI(uri any) *MockSender_OpenURI_Call {
	return &MockSender_OpenURI_Call{Call: _e.mock.On("OpenURI", uri)}
}

func (_c *MockSender_OpenURI_Call) Run(run func(uri string)) *MockSender_OpenURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_OpenURI_Call) Return(err error) *MockSender_OpenURI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_OpenURI_Call) RunAndReturn(run func(uri string) error) *MockSender_OpenURI_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSender
func (_mock *MockSender) Send(n notify.Notification) (uint32, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(notify.Notification) (uint32, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(notify.Notification) uint32); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(notify.Notification) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - n notify.Notification
func (_e *MockSender_Expecter) Send(n any) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", n)}
}

func (_c *MockSender_Send_Call) Run(run func(n notify.Notification)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 notify.Notification
		if args[0] != nil {
			arg0 = args[0].(notify.Notification)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(v uint32, err error) *MockSender_Send_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(n notify.Notification) (uint32, error)) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
